ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'BOOKS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'DIANETICS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SCIENTOLOGY';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'LOCAL_SERVICES';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'HOME_SERVICES';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'PROFESSIONAL_SERVICES';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SOFTWARE';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'WEB_APPS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SECURITY';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'EDUCATION';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'WRITING';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'MANUSCRIPTS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'PHOTOGRAPHY';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'GALLERY';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'MUSIC';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'VIDEO';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'HEALTH';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'FITNESS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'FOOD';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'TRAVEL';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'REAL_ESTATE';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'AUTOMOTIVE';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'VOLUNTEERING';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'COMMUNITY';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'NEWS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'POLITICS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SPIRITUALITY';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SELF_IMPROVEMENT';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'PRODUCTIVITY';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'ENTREPRENEURSHIP';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'ART';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'DESIGN';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'GAMING';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'PETS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'OUTDOORS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SPORTS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'PARENTING';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'RELATIONSHIPS';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'ENTERTAINMENT';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SHOPPING';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'EQUIPMENT';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'SUPPLIES';
ALTER TYPE "InterestCategory" ADD VALUE IF NOT EXISTS 'ELECTRONICS';

ALTER TABLE "AdCampaign"
  ADD COLUMN "targetAgeRanges" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "targetSexes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "targetHashtags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
