import type { MarketplaceListingKind } from "./marketplace.contracts";

export type MarketplaceTaxonomyCategory = {
  label: string;
  subcategories: readonly string[];
};

export const MARKETPLACE_TAXONOMY: Record<MarketplaceListingKind, readonly MarketplaceTaxonomyCategory[]> = {
  GOODS: [
    { label: "Furniture & Decor", subcategories: ["Living room", "Bedroom", "Dining room", "Office", "Outdoor", "Storage", "Custom furniture"] },
    { label: "Electronics", subcategories: ["Computers", "Phones", "TV & audio", "Cameras", "Gaming", "Smart home", "Accessories"] },
    { label: "Appliances", subcategories: ["Kitchen", "Laundry", "Cleaning", "Heating & cooling", "Small appliances"] },
    { label: "Clothing", subcategories: ["Women", "Men", "Children", "Workwear", "Formal wear", "Vintage clothing"] },
    { label: "Shoes & Accessories", subcategories: ["Shoes", "Bags", "Hats", "Belts", "Sunglasses", "Other accessories"] },
    { label: "Jewelry & Watches", subcategories: ["Fine jewelry", "Fashion jewelry", "Watches", "Handmade jewelry", "Supplies"] },
    { label: "Home & Garden", subcategories: ["Kitchenware", "Bedding", "Lighting", "Garden", "Plants", "Home improvement", "Seasonal"] },
    { label: "Tools & Equipment", subcategories: ["Hand tools", "Power tools", "Workshop equipment", "Lawn equipment", "Construction equipment"] },
    { label: "Books & Media", subcategories: ["Books", "Magazines", "Movies", "Music", "Educational materials", "Rare & collectible"] },
    { label: "Art & Collectibles", subcategories: ["Original art", "Prints", "Photography", "Sculpture", "Memorabilia", "Antiques", "Collectibles"] },
    { label: "Handmade & Vintage", subcategories: ["Handmade home goods", "Personalized gifts", "Vintage goods", "Upcycled goods", "Digital designs"] },
    { label: "Craft Supplies", subcategories: ["Fabric", "Yarn", "Paper crafts", "Jewelry making", "Woodworking", "Art supplies", "Patterns"] },
    { label: "Musical Instruments", subcategories: ["Guitars", "Keyboards", "Drums", "Orchestral", "Live sound", "Recording equipment"] },
    { label: "Sports & Outdoors", subcategories: ["Fitness", "Camping", "Cycling gear", "Water sports", "Team sports", "Hunting & fishing"] },
    { label: "Kids & Baby", subcategories: ["Baby gear", "Nursery", "Toys", "Children's furniture", "School supplies"] },
    { label: "Health & Beauty", subcategories: ["Personal care", "Hair care", "Skin care", "Wellness", "Salon equipment"] },
    { label: "Pet Supplies", subcategories: ["Dogs", "Cats", "Birds", "Aquariums", "Small animals", "Farm animals"] },
    { label: "Office & Business", subcategories: ["Office supplies", "Retail fixtures", "Restaurant equipment", "Shipping supplies", "Commercial equipment"] },
    { label: "Event & Wedding", subcategories: ["Decor", "Tableware", "Lighting", "Signage", "Costumes", "Wedding supplies"] },
    { label: "Free & Trade", subcategories: ["Free items", "Swap or trade", "Curb alert"] },
    { label: "General", subcategories: ["Household", "Miscellaneous"] },
    { label: "Other", subcategories: [] },
  ],
  VEHICLE: [
    { label: "Cars", subcategories: ["Sedan", "Hatchback", "Coupe", "Convertible", "Electric"] },
    { label: "Trucks", subcategories: ["Light duty", "Heavy duty", "Utility", "Classic trucks"] },
    { label: "SUVs & Crossovers", subcategories: ["Compact SUV", "Midsize SUV", "Full-size SUV", "Electric SUV"] },
    { label: "Vans", subcategories: ["Passenger van", "Cargo van", "Camper van", "Minivan"] },
    { label: "Motorcycles", subcategories: ["Street", "Cruiser", "Touring", "Off-road", "Scooters"] },
    { label: "Bicycles", subcategories: ["Road", "Mountain", "Electric", "Commuter", "Children's bikes"] },
    { label: "RVs & Campers", subcategories: ["Motorhome", "Travel trailer", "Fifth wheel", "Pop-up camper"] },
    { label: "Boats & Watercraft", subcategories: ["Powerboats", "Sailboats", "Personal watercraft", "Kayaks & canoes"] },
    { label: "Commercial Vehicles", subcategories: ["Box trucks", "Buses", "Trailers", "Farm vehicles", "Heavy equipment"] },
    { label: "Parts & Accessories", subcategories: ["Engine parts", "Wheels & tires", "Interior", "Exterior", "Electronics", "Tools"] },
    { label: "Other", subcategories: [] },
  ],
  RENTAL: [
    { label: "Apartments", subcategories: ["Studio", "One bedroom", "Two bedroom", "Three-plus bedrooms"] },
    { label: "Houses", subcategories: ["Detached", "Townhouse", "Duplex", "Cottage"] },
    { label: "Rooms & Shared Housing", subcategories: ["Private room", "Shared room", "Roommate wanted", "Sublet"] },
    { label: "Short-term Stays", subcategories: ["Vacation rental", "Monthly stay", "Guest suite", "Corporate housing"] },
    { label: "Commercial Property", subcategories: ["Office", "Retail", "Warehouse", "Workshop", "Restaurant space"] },
    { label: "Land", subcategories: ["Residential land", "Agricultural", "Recreational", "Commercial land"] },
    { label: "Storage & Parking", subcategories: ["Storage unit", "Garage", "Parking space", "RV or boat storage"] },
    { label: "Housing Wanted", subcategories: ["Apartment wanted", "House wanted", "Room wanted", "Roommate wanted"] },
  ],
  SERVICE: [
    { label: "Home Repair & Maintenance", subcategories: ["Handyman", "Plumbing", "Electrical", "HVAC", "Roofing", "Painting"] },
    { label: "Construction & Trades", subcategories: ["General contracting", "Carpentry", "Masonry", "Flooring", "Landscaping", "Architecture"] },
    { label: "Cleaning", subcategories: ["Home cleaning", "Office cleaning", "Carpet cleaning", "Pressure washing", "Junk removal"] },
    { label: "Moving & Storage", subcategories: ["Local moving", "Long-distance moving", "Packing", "Hauling", "Storage help"] },
    { label: "Automotive Services", subcategories: ["Repair", "Detailing", "Tires", "Towing", "Inspection", "Mobile mechanic"] },
    { label: "Technology", subcategories: ["IT support", "Web development", "App development", "Cybersecurity", "Data recovery", "Cloud services"] },
    { label: "Professional Services", subcategories: ["Legal", "Accounting", "Bookkeeping", "Consulting", "Translation", "Notary"] },
    { label: "Business Services", subcategories: ["Marketing", "Advertising", "Sales support", "Operations", "Printing", "Business planning"] },
    { label: "Creative Services", subcategories: ["Graphic design", "Photography", "Video", "Writing", "Music & audio", "Interior design"] },
    { label: "Education & Tutoring", subcategories: ["Academic tutoring", "Language lessons", "Music lessons", "Professional training", "Test preparation"] },
    { label: "Events", subcategories: ["Planning", "Catering", "Entertainment", "Rentals", "Decor", "Venue services"] },
    { label: "Transport & Delivery", subcategories: ["Courier", "Local delivery", "Airport transport", "Freight", "Personal driver"] },
    { label: "Care Services", subcategories: ["Child care", "Elder care", "House sitting", "Personal assistance"] },
    { label: "Health & Wellness", subcategories: ["Fitness", "Nutrition", "Massage", "Wellness coaching"] },
    { label: "Beauty & Personal Care", subcategories: ["Hair", "Makeup", "Nails", "Barbering", "Personal styling"] },
    { label: "Pet Services", subcategories: ["Pet sitting", "Dog walking", "Grooming", "Training", "Boarding"] },
    { label: "Travel & Hospitality", subcategories: ["Travel planning", "Tour guide", "Hospitality staffing", "Property hosting"] },
    { label: "Other", subcategories: [] },
  ],
  JOB: [
    { label: "Administration", subcategories: ["Office administration", "Executive assistant", "Data entry", "Reception"] },
    { label: "Accounting & Finance", subcategories: ["Accounting", "Bookkeeping", "Payroll", "Financial analysis"] },
    { label: "Customer Service", subcategories: ["Customer support", "Call center", "Client success", "Help desk"] },
    { label: "Sales & Business Development", subcategories: ["Inside sales", "Field sales", "Account management", "Business development"] },
    { label: "Marketing & Communications", subcategories: ["Digital marketing", "Content", "Public relations", "Social media"] },
    { label: "Technology", subcategories: ["Software development", "IT support", "Cybersecurity", "Data", "Product management"] },
    { label: "Engineering", subcategories: ["Civil", "Mechanical", "Electrical", "Industrial", "Quality"] },
    { label: "Construction & Skilled Trades", subcategories: ["Carpentry", "Electrical", "Plumbing", "Equipment operator", "Site management"] },
    { label: "Education & Training", subcategories: ["Teaching", "Tutoring", "Instructional design", "Training"] },
    { label: "Healthcare & Wellness", subcategories: ["Clinical", "Dental", "Fitness", "Caregiving", "Administration"] },
    { label: "Creative & Design", subcategories: ["Graphic design", "Writing", "Photography", "Video", "UX design"] },
    { label: "Hospitality & Food Service", subcategories: ["Restaurant", "Hotel", "Catering", "Events"] },
    { label: "Transport & Logistics", subcategories: ["Driving", "Delivery", "Warehouse", "Dispatch", "Supply chain"] },
    { label: "Retail", subcategories: ["Store operations", "Merchandising", "Buying", "Loss prevention"] },
    { label: "Manufacturing", subcategories: ["Production", "Machining", "Assembly", "Maintenance", "Quality control"] },
    { label: "Real Estate", subcategories: ["Property management", "Leasing", "Sales", "Maintenance"] },
    { label: "Nonprofit & Community", subcategories: ["Program management", "Fundraising", "Community outreach", "Volunteer"] },
    { label: "Remote & Freelance", subcategories: ["Remote full-time", "Freelance", "Contract", "Project work"] },
    { label: "Other", subcategories: [] },
  ],
  AUDITOR: [
    { label: "Field Auditors", subcategories: ["Local auditing", "Traveling auditor", "Remote consultation"] },
    { label: "Field Groups", subcategories: ["Local field group", "Dianetics group", "Course delivery"] },
    { label: "Class V Orgs", subcategories: ["Church services", "Academy training", "Introductory services"] },
    { label: "SH/AO", subcategories: ["Saint Hill", "Advanced Organization"] },
    { label: "FLAG", subcategories: ["Flag services"] },
    { label: "Auditing Wanted", subcategories: ["Local auditor wanted", "Traveling auditor wanted", "Service guidance"] },
  ],
};

export function marketplaceCategoryLabels(kind: MarketplaceListingKind) {
  return MARKETPLACE_TAXONOMY[kind].map((category) => category.label);
}

